version: '3'
services:
  formatif-dev-container:
    container_name: dbtest-formatif-dev-container
    build:
      context: ../
      dockerfile: dev.Dockerfile
    volumes:
      # Mounts the project folder to '/workspace'. While this file is in .devcontainer,
      # mounts are relative to the first file in the list, which is a level up.
      - ..:/workspace:cached
      - formatif_tmp_compose:/workspace/tmp
      - formatif_student-work_compose:/student-work
      - ws_node_modules:/workspace/node_modules
      - web_node_modules:/workspace/doubtfire-web/node_modules
      # - formatif_db_compose:/var/lib/mysql
      - formatif_gems_compose:/home/vscode/.gems
    ports:
      - "9876:9876"
      - "4200:4200"
      - "3000:3000"
    # Overrides default command so things don't shut down after the process ends.
    command: /bin/sh -c "while sleep 5000; do :; done"
    env_file:
      - devcontainer.env
    depends_on:
      - dev-db
    
  dev-db:
    container_name: doubtfire-dev-db
    image: mariadb:10
    restart: always
    # platform: linux/amd64
    volumes:
      # - ./:/workspace/.devcontainer/
      - formatif_tmp_compose:/var/lib/mysql
    env_file:
      - ./devcontainer.env
    networks:
      - default


volumes:
  ws_node_modules:
  web_node_modules:
  formatif_tmp_compose:
  formatif_student-work_compose:
  formatif_db_compose:
  formatif_gems_compose:
